name: TCASample

options:
  bundleIdPrefix: com.sakatakeisuke
  deploymentTarget:
    iOS: 14.0
  xcodeversion: "14.3"
  createIntermediateGroups: true
  createProductStructure: false

settings:
  base:
    MARKETING_VERSION: 1.0.0

targets:
  TCASample:
    type: application
    platform: iOS
    sources:
      - path: TCASample
      - path: TCASample/Resources/Generated/Assets.swift
        optional: true
      - path: TCASample/Resources/Generated/LocalizableStrings.swift
        optional: true
    info:
      path: Info.plist
      properties:
        CFBundleVersion: "0"
        CFBundleShortVersionString: $(MARKETING_VERSION)
    dependencies:
      - package: TheComposableArchitecture
        product: ComposableArchitecture
    preBuildScripts:
      - name: swiftgen
        path: XCodeGen/Scripts/SwiftGen.sh
        outputFiles:
          - $(SRCROOT)/TCASample/Resources/Generated/Assets.swift
          - $(SRCROOT)/TCASample/Resources/Generated/LocalizableStrings.swift
      - name: swiftlint
        path: XCodeGen/Scripts/SwiftLint.sh
        basedOnDependencyAnalysis: false

schemes:
  TCASample:
    build:
      targets:
        TCASample: [analyze, run, archive]

packages:
  TheComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    exactVersion: 0.52.0